<a href="https://colab.research.google.com/github/nithinpvarkey/neural_network_pytorch/blob/main/Neural_network_and_pytorch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

*In PyTorch, a **Tensor** is the fundamental data structure, similar to NumPy arrays but with additional capabilities, such as GPU acceleration and automatic differentiation.*

In [11]:
# Scalar (0D tensor)
scalar = torch.tensor(5)
scalar     # Output: tensor(5)--> This means "a tensor containing the value 5."
print(scalar.shape)


# Vector (1D tensor)
vector = torch.tensor([1,2,3])
vector                    # output : tensor([1,2,3])
print(vector.shape)

matrix = torch.tensor([[1, 2], [3, 4]])
print(matrix.shape)  # Output: torch.Size([2, 2])
matrix

# 3D Tensor
tensor_3d = torch.rand(2, 3, 4)  # Random tensor of shape (2,3,4)
print(tensor_3d.shape)   # Output: torch.Size([2, 3, 4])
tensor_3d

torch.Size([])
torch.Size([3])
torch.Size([2, 2])
torch.Size([2, 3, 4])


tensor([[[0.4780, 0.8451, 0.1578, 0.7977],
         [0.7069, 0.1917, 0.9210, 0.7699],
         [0.1962, 0.3690, 0.8747, 0.3862]],

        [[0.5513, 0.1703, 0.7970, 0.4380],
         [0.2904, 0.0886, 0.8022, 0.9744],
         [0.2856, 0.6591, 0.2445, 0.0432]]])

In [13]:
integer = torch.tensor(1234)
decimal = torch.tensor(3.14159265359)
print(f"`integer` is a {integer.ndim}-d Tensor: {integer}")
print(f"`decimal` is a {decimal.ndim}-d Tensor: {decimal}")


`integer` is a 0-d Tensor: 1234
`decimal` is a 0-d Tensor: 3.1415927410125732


tensor(1234)

**Basic Tensor Operations**

In [11]:
#addition
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
sum_tensor = a + b
print("Sum:", sum_tensor)

# Multiplication (element-wise)
mul_tensor = a * b
print("Element-wise multiplication:", mul_tensor)

# Matrix multiplication
c = torch.tensor([[1, 2], [3, 4]])
d = torch.tensor([[5, 6], [7, 8]])
matmul_tensor = torch.matmul(c, d)
print("Matrix multiplication:\n", matmul_tensor)


# Reshape a tensor
e = torch.tensor([1, 2, 3, 4, 5, 6])
reshaped = e.view(2, 3)
print("Reshaped tensor:\n", reshaped)



Sum: tensor([5, 7, 9])
Element-wise multiplication: tensor([ 4, 10, 18])
Matrix multiplication:
 tensor([[19, 22],
        [43, 50]])
Reshaped tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])


**NEURAL NETWORK IN PYTORCH**

PyTorch uses **torch.nn.Module**, which serves as a base class for all neural network modules in PyTorch and thus provides a framework for building and training neural networks.

We will use **torch.nn.Module** to define layers. when we implement a layer, we subclass nn.Module and define the parameters of the layer as attributes of our new class.



In [15]:
#define a dense layer
class MyDenseLayer(torch.nn.Module):
  def __init__(self,number_inputs,number_outputs):
    super(MyDenseLayer, self).__init__()
    self.weights = torch.nn.Parameter(torch.randn(number_inputs,number_outputs))
    self.bias = torch.nn.Parameter(torch.randn(number_outputs))

  def forward(self,x):
    z =  torch.matmul(x,self.weights) + self.bias
    y = torch.sigmoid(z)
    return y


In [17]:
# NOW TEST OUTPUT OF OUR LAYER
number_inputs = 3
number_outputs = 4
LAYER = MyDenseLayer(number_inputs,number_outputs)
x = torch.randn(1,number_inputs)
y = LAYER(x)
print(y)

tensor([[0.7917, 0.2175, 0.4438, 0.6602]], grad_fn=<SigmoidBackward0>)
